# default values for openstack umbrella chart
# Global overrides for subcharts

# note(v-dspecker): helm3_hook must be disabled
# There is a cyclic dependency otherwise. For example, libvirt-default ->
# nuetron-ovs-agent-default -> neutron-server -> neutron-ks-user.
# Since libvirt-default is deployed during install phase, neutron-ks-user must also
# be installed during install phase instead of post-install phase.

global:
  subchart_release_name: true

helm-toolkit:
  enabled: true

rabbitmq:
  release_group: rabbitmq
  enabled: true
  volume:
    enabled: false
  pod:
    replicas:
      server: 1

mariadb:
  release_group: mariadb
  enabled: true
  pod:
    replicas:
      server: 1
  volume:
    enabled: false
    use_local_path_for_single_pod_cluster:
      enabled: true

memcached:
  release_group: memcached
  enabled: true

keystone:
  release_group: keystone
  enabled: true

heat:
  release_group: heat
  enabled: true
  helm3_hook: false

glance:
  release_group: glance
  enabled: true
  helm3_hook: false

openvswitch:
  release_group: openvswitch
  enabled: true

libvirt:
  release_group: libvirt
  enabled: true

nova:
  release_group: nova
  enabled: true
  helm3_hook: false

placement:
  release_group: placement
  enabled: true
  helm3_hook: false

neutron:
  release_group: neutron
  enabled: true
  helm3_hook: false
  conf:
    auto_bridge_add:
      # no idea why, but something with sub-charts and null values get ommitted entirely from sub chart
      br-ex: "null"
